### ISSUE TITLE
Idea: Make a configurable database of phrases the ducky could say to get you unstuck

### ISSUE THREAD

**Issue by masterpi314** [RameshAditya/ducky#1]
Examples:

"Have you tried turning it off and on again?"
"Could it have something to do with timezones?"
"What assumptions are you making?"

**Comment by RameshAditya** [comment]
@masterpi314 Hm, that's clever. I'll leave this issue open in case anyone interested wants to volunteer - else I'll make a commit implementing this later.

Thanks for the idea! 🙂

**Comment by Nibot1** [comment]
take a look at this [https://developer.chrome.com/apps/tts](url)

**Comment by vshining** [comment]
@Nibot1  I think a ballon with a phrase showing when clicking on the ducky (with the quack sound) would be more appropriate - TTS is a little bit over the top.

**Comment by Nibot1** [comment]
@vshining I think you are right and the speech bubble is a great Idea
